// Generated by CoffeeScript 1.6.2
$(function(){
	 $('.carousel').carousel({
	      interval: 2000
	    });
	    $('#videoDiv').hide();
	    $('.play').bind('click', function(){
	    	var path = $(this).attr('vpath');
	    	var chs = '<video class="video-js vjs-default-skin" controls autoplay="autoplay" preload="auto" width="800" height="600" poster="my_video_poster.png" data-setup="{}"><source id="myvideo" src="'+path+'" type="video/mp4"></source></video>';
	    	$('#myvideo').empty().append(chs);
	    	//comments
	    	var vid = $(this).attr("vid");
	    	 $.ajax({
				  url:'comments?action=list&videoid=' + vid,
				  dataType:'json',
				  cache:false,
				  success:function(coms){
					  var comtable='<table id="ctable" class="table table-striped"><thead><tr><th>评论人</th><th>评论时间</th><th>评论内容</th></tr></thead><tbody>';
					  //var coms = eval("(" + data.data + ")");
					  
					  for(var i = 0; i < coms.length; i++){
						  var publishDate = (coms[i].publishDate.year + 1900) + "-" + (coms[i].publishDate.month + 1) + "-" + coms[i].publishDate.date;
						  if(i % 2 == 0){
							  comtable += '<tr><td>' + coms[i].userName + '</td><td>' + publishDate + '</td><td>' + coms[i].content + '</td></tr>';

						  }else{
							  comtable += '<tr class="success"><td>' + coms[i].userName + '</td><td>' + publishDate + '</td><td>' + coms[i].content + '</td></tr>';
						  }
						  
					  }
					  comtable += '</tbody></table>';
					  comtable += '<div class="container><div class="row-fluid"><div class="span12"><div id="errinfo"></div><fieldset><legend>发表评论</legend> <label>用户名</label><input id="uname" type="text" /> <label>内  容</label><input id="ccontent" type="text" /> <br /><button id="btnaddcm" class="btn btn-info">提  交</button></fieldset></div></div><div>';
					  $('#comments').empty().append(comtable);
					  $('#addcom').wysiwyg();
					  
					  var count = 0;
					  $('#btnaddcm').bind('click', function(){
						  var uname = $('#uname').val();
						  var ccontent = $('#ccontent').val();
						  if(uname == '' || ccontent == ''){
							  var err = '<div class="alert"><button type="button" class="close" data-dismiss="alert">×</button><h4>提示!</h4> <strong>警告!</strong> 用户名和密码都不能为空.</div>';
							  $('#errinfo').empty().append(err);
						  }else{
							  var cc;
							  var date = new Date();
							  var publishDate = date.getFullYear() + "-" + (date.getMonth() + 1) + "-" + date.getDate();
							  if(count % 2 == 0){
								  cc = '<tr class="success"><td>' + uname + '</td><td>' + publishDate + '</td><td>' + ccontent + '</td></tr>';
							  }else{
								  cc = '<tr><td>' + uname + '</td><td>' + publishDate + '</td><td>' + ccontent + '</td></tr>';
							  }
							  count++;
							  $('#ctable').prepend(cc);
							  $('#errinfo').empty();
							  //post to server side
							  $.ajax({
								  url: 'comments?action=save&videoid=' + vid + '&uname=' + uname + '&content=' + ccontent,
								  type: 'POST',
								  contentType: "application/x-www-form-urlencoded; charset=utf-8",
								  success: function(data){
									  
								  }
							  });
						  }
					  });
				  }
	    	 });
	    	$('#videoDiv').slideDown("slow"); 
	    });
});